//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
// Created via this command line: "C:\Users\voing\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://education.crm2016.uds.systems/education" /generateActions /out:"C:\Users\voing\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\Actions.cs" /namespace:"CrmEarlyBound" /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"uds\b.voinyk" /password:"******" /domain:"https://education.crm2016.uds.systems" 
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_deactivationofchildentities1bccb6cb45f5ea11812900155d06f203")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class new_deactivationofchildentities1bccb6cb45f5ea11812900155d06f203Request : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_deactivationofchildentities1bccb6cb45f5ea11812900155d06f203Request()
		{
			this.RequestName = "new_deactivationofchildentities1bccb6cb45f5ea11812900155d06f203";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_deactivationofchildentities1bccb6cb45f5ea11812900155d06f203")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class new_deactivationofchildentities1bccb6cb45f5ea11812900155d06f203Response : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_deactivationofchildentities1bccb6cb45f5ea11812900155d06f203Response()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rwb/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("rwb_CustomiseRibbon")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class rwb_CustomiseRibbonRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Operation
		{
			get
			{
				if (this.Parameters.Contains("Operation"))
				{
					return ((string)(this.Parameters["Operation"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Operation"] = value;
			}
		}
		
		public string Data
		{
			get
			{
				if (this.Parameters.Contains("Data"))
				{
					return ((string)(this.Parameters["Data"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Data"] = value;
			}
		}
		
		public rwb_CustomiseRibbonRequest()
		{
			this.RequestName = "rwb_CustomiseRibbon";
			this.Operation = default(string);
			this.Data = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rwb/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("rwb_CustomiseRibbon")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class rwb_CustomiseRibbonResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public rwb_CustomiseRibbonResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
